const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "",eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUVPaTdHSVd0cGwvaTZVT0d2NE9XaFRuYms4MXVPdG1ET0VQQUtKMDNrOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoienQzamcxT3FvbXI1M1plSXdFb29sMGw2b3h5eTZkc1NId2Rtc2hGZE14dz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnRmN4Y3VQMGk2ZmZ1TjR1d2VIMmNVeXVTODliYXltZ2N2Yzh4cG5EVEhRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5eDdCelZIQ1pZdTkvZWMvZmlaNjFuSk5KaDJhRkhZbWpjQmZrYU1RdlJZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlMN1JtYjJIWW5zMEphT09lR3dydVdQd1h4NTZHMXV4MGE2NmVBZFp5RkE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFMVVdoUzBUalBUUnhqVkJpNEZ1VDc4clNBRThBQmdWRWRHK3p5eXRBMjQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZU1YY1U1cHdTZkxPUVVZd3JHZDdnMkxtVmIvZFV4djRpL3BGVXZabGkxND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiazFiQUlTaGExQVltbzlhZkdFd2g4Q0VnQ1BYcWdlZ0ZuTDZvNjh4ZlFBUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlhrbHFWVWR0TVpYLzRNWEhVQmo1QkxCeUtXOGttajlGRE1xUEhhM2RhOXg1ZDFiZmNnaFp6eXZZVDNKVmlkODhhNTJia1M1bko1WEZuQ25yZnhvaWpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQzLCJhZHZTZWNyZXRLZXkiOiI1bkx3aVZlbE1EUE9jVlp3OSsvcXdkdTc2MzNkOW5CU2owY0VTZWhLNUJBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxMDE1NDY1M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzMDI3N0I0OTNGRTdEMDgyMDJFNUUzMzZCQjExOThCMyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ0NzE4MTQ2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MTAxNTQ2NTNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMjRDMTdBOEQ2NkVDNkU2NDA3MDRERjU2OUFDRUI1RjEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0NDcxODE1MX1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMU4tc0lBbHlSaG1aaUZBQnJsYWRZQSIsInBob25lSWQiOiJiNGNiNGRiMy02MzU4LTRhZDgtYTczZC0xM2FlYTEwZGNhMjkiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTSs0VHJualVGMDEyMGVVbTJQNVR5bWVJYlJFPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilg3NEMvYmpJRXZuc3dhTEtDTnNpakUrQkFUdz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI5WEFZNENGUyIsIm1lIjp7ImlkIjoiMjU0NzEwMTU0NjUzOjE3QHMud2hhdHNhcHAubmV0IiwibmFtZSI6Ildlc2xleSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUEtvNXBJSEVLS1MrYjhHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiTmdpVVZkbU1RRDZUdkpFdlJVTTNJRGRVRjUrY2pnVnlENHNXL3N0RmhFOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiUzBiRGw1SDdTbzZFZG13UkZzU2RYZTI3dEQ4dGNzYSs5anVxcG5VdmcwcXMvR2ZTK2xRT2NaMGFPakludmUwSEVzbkVaMVdKZlRyaFg5TEw1VW9DRHc9PSIsImRldmljZVNpZ25hdHVyZSI6ImF4UFZidVAvZUFPcUlSeTNscFFTSEhrUjhVbHVWaU9SQm9FRGJ6VTNyMFJISTFXNU1WNlU3MGttb1ZzZjJOQU5tVG1sdlFvdTZiWHRNbk1CbG1YRmlnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzEwMTU0NjUzOjE3QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlRZSWxGWFpqRUErazd5UkwwVkROeUEzVkJlZm5JNEZjZytMRnY3TFJZUlAifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDQ3MTgxMjgsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBS0k1In0=
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
